title: Python Docs
description: Course materials for Post-AP Computer Science
theme: just-the-docs

url: https://katerinanavab.github.io/pythondocs

logo: "assets/logo-pythondocs.png"
favicon_ico: "favicon.ico"

aux_links_new_tab: true
aux_links:
  "DevDocs":
    - "https://devdocs.io/"
  "Replit":
    - "https://replit.com/~"
  "Blackbaud":
    - "https://bwl.myschoolapp.com/app#login"
    
back_to_top: true
back_to_top_text: "⬆️ BACK TO TOP"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

