title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://katerinanavab.github.io/pythondocs

aux_links:
  "Instructor Site":
    - "https://coderina.dev"

logo: "logo-postapcs.png"
favicon_ico: "logo-postapcs.png"

back_to_top: true
back_to_top_text: "⬆️ BACK TO TOP"
